commonmark/commonmark-spec

COPYING
Makefile

This update clarifies the provenance and license of buffer.h,
buffer.c, chunk.h, utf8.h, utf8.c.
@vmg certifies by merging this PR that the license and copyright
information are accurate.

Updated LICENSE, renamed to COPYING.

---

js/lib/blocks.js

It looks like the line is unused (the property is on Node objects).

Dead code: Remove line assigning to Parser's _lastLineBlank property

---

js/lib/blocks.js

In other cases, there is no return, and no caller checks for a return
value.

Remove unnecessary return of value

---

Makefile
README.md

This pull request improves the build process in several ways:
- `cmake` is only run once when `make` is invoked for the first time.
Subsequent calls to `make` don't reconfigure the project.
- `make INSTALL_PREFIX=path` can be used to specify the install prefix.
- `make test` automatically (re)builds the project before running tests.

Makefile fixes

---

spec.txt

Please see the diff. It clearly looks as a mistake to me.

mistake in examples of left/right flanking delims

---

spec.txt

The behavior was already specified in examples 426, 427, 428, 440, 441; this change merely describes it in the textual part.
I am not set on this particular phrasing; feel free to decline this PR and phrase it differently. I just stumbled over this and feel it should be spelled out in writing.

Specify nested link definition behavior in prose

---

spec.txt

Consider adding these (or similar) examples showing the use of fragment identifiers in links.  These examples can help implementors avoid errors special characters in links.

add spec examples showing the use of fragment identifiers in links

---

spec.txt

It's already listed in alphabetical order on the next line.

Don't list "title" twice as HTML block tag

---

spec.txt

This makes sure that implementations skip columns instead of offsets for
continued indented code blocks.
Background: I was implementing the new tab logic and was surprised that
all the spec tests passed even though I hadn't changed the continuation
logic of indented code blocks to skip columns. The added example checks
this.

Add an example with mixed indentation code block in "Tabs" section

---

spec.txt

Here's the discussion that led to this pull request: http://talk.commonmark.org/t/code-block-with-empty-lines-within-a-list-item/1941

New test case: list item code block with empty line

---

spec.txt

After implementing the changes for the 0.25 spec, all the spec tests
were green.
But I noticed that my code also counted the spaces on the first line and
required the subsequent lines to be indented accordingly. This example
catches that possible bug.

Add example for list item starting with a blank line with spaces

---

spec.txt

Hi jgm,
This is a PR to slightly change an existing test for nested list items to add another level which has an indent > 4 chars, as I came across a bug in Markdig, and the specs didn't trigger this one.

Add test case for nested lists with an indent > 4

---

spec.txt

Hi jgm,
I came with a regression recently and it was due to the fact that my parser was not detecting proper end tag, but specs didn't detect this. So I have added to some relevant cases a simple paragraph `okay` which makes sure that Markdown parsing is catching up after an HTML end block tag.

Improve tests for HTML end block parsing

---

spec.txt

The definition of a list still said that "two blank lines end all
containing lists." That rule has been removed.

Update statement on blank lines and lists.

---

spec.txt

In light of jgm/commonmark.js#107, add a few examples/test cases to make sure the distinction between Unicode whitespace and regular whitespace is kept.

Add examples for Unicode whitespace

---

index.js
package.json

__package.json__
- File is correct, but you probably wish to update some fields.
- `version` field should be updated by scripts as part of publish process.
__index.js__
- now has only `require('commonmark-spec').text`
- if someone needs json/xml formats, those can be added later as `require('commonmark-spec').json` etc.
Quick check from CLI:
```bash
node -e "console.log(require('./').text)"
```
If you don't like to merge this intermediate results - feel free to use it as you wish.

Added drafts to publish spec in npm, #394

---

spec.txt

This tripped me up when I was looking for a method in a unicode library.

`Zs` is a general category not a class

---

spec.txt

Escaping `[` disables the markup, escaping `!` on top of that doesn't change anything and is therefore misleading in this example.

Example for disabling image markup: remove a backslash

---

spec.txt

I guess this would have passed a spell checker since *theses* is the plural of *thesis*.
Listing the number of spaces the first tab is expanded into reduces the cognitive load required to figure out why the next line talks about six spaces.

Fix typo and clarify expansion

---

spec.txt

This is covered by example 60 (and probably others) as well, but it would be nice to have an example for it in the fenced code block section.

Add fenced code block example with not enough backticks.

---

spec.txt

There already exists the statement: "When both a thematic break and a list item are possible
interpretations of a line, the thematic break takes precedence".
This adjustment ensures that this precedence is achieved by the list item definition.

Clarify precedence of thematic break

---

spec.txt

According to the JS reference implementation, these are matching link labels, although one is surrounded by spaces:
```
[ a ]: b
[a]
```
---
On a related note: It is not quite clear if the brackets themselves are part of the *link label* or not.
> A [link label](http://spec.commonmark.org/0.27/#link-label) begins with a left bracket (`[`) and ends with the first right bracket (`]`) that is not backslash-escaped.
The words "begin" and "end" sound like the brackets are included.
However, that can't be, because it's not allowed:
> Unescaped square bracket characters are not allowed in link labels.
*If* the brackets are part of the link label, the word *internal* whitespace doesn't quite mean what it's supposed to mean.
My English-fu isn't good enough to suggest an improvement in wording.

Mention removing surrounding whitespace from link labels

---

Makefile

Having this in the MakeFile makes it that much easier to produce the `spec.json` in a way that is analogous to the other forms of the spec document.

Add spec.json generator to Makefile

---

README.md
changelog.txt
package.json

It appears that the repositories have been moved to a GitHub organization. This fixes the links to the CommonMark, cmark and commonmark.js repositories.

Update GitHub links

---

spec.txt

As noted in https://github.com/github/cmark/issues/60, the info string is not only trimmed of "spaces" (U+0020) but indeed all whitespace.  Update the spec to reflect this.
Likewise, "spaces" is changed to "spaces or tabs" following a thematic break, per the scanner.

Info string is trimmed of all whitespace

---

spec.txt

Example 116 is:
```
<table><tr><td>
<pre>
**Hello**,
_world_.
</pre>
</td></tr></table>
```
But `**Hello**` is lowercased in the document.

Fix a typo in spec.txt

---

CommonMark.dtd

The DTD defines a 'url' attribute for an image, however both cmark and CommonMark.js appear to use 'destination' instead (which is also consistent with a link).
http://spec.commonmark.org/dingus/
```
```
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "CommonMark.dtd">
<document xmlns="http://commonmark.org/xml/1.0">
<paragraph>
<image destination="/url" title="title">
<text>foo</text>
</image>
</paragraph>
</document>
```
This MR updates the DTD to use 'destination' instead of 'url'. I couldn't see any other references in the spec indicating which attribute is actually correct, but if it is the case that cmark/commonmark.js are actually incorrect and not following the DTD, please close this.

Replace image 'url' with 'destination' in DTD

---

spec.txt

At a couple places in the spec (https://spec.commonmark.org/0.28/#container-blocks-and-leaf-blocks, for example) the references to the container- and leaf- block section headers were using the singular form, even though the headers themselves are plural.

Typo Fix: container- and leaf-block references

---

tools/template.html

Currently, double clicking on Markdown code on https://spec.commonmark.org/0.28/ always opens https://spec.commonmark.org/dingus/?text= without content prefill. This PR fixes that bug.

Fix dingus link when double clicking Markdown code

---

spec.txt

Remove spurious parenthesis, rephrase for clarity (issue [#555](https://github.com/commonmark/CommonMark/issues/555)).
More lines seem changed (because `emacs fill-paragraph`), 
but only one sentence was modified. I'll change the pull request 
if this is a problem.

fix typo in spec (issue #555)

---

spec.txt

Change "If none in found" to "If none is found"

Fix typo in spec

---

spec.txt

This now tests that an entity with 8 arabic digits is no longer recognised

Test new entity length constraints

---

spec.txt

A code span can have more than its two surrounding ones, like ` `` `.

Clarify which backtick strings

---

spec.txt

My first attempt at writing a parser added new blocks to the last
matched block, regardless if it was a container or leaf. I think it
would have helped me if it had explicitly said "container" here.

Clarify that new blocks are added to *container* blocks.

---

spec.txt

This PR removes superfluous restrictions on declarations that CM currently imposes, whereas HTML is more relaxed.
This is mostly useful because `<!doctype html>` can be used in HTML, but couldn’t be used in CM before.
Theoretically, this could make more user input HTML, which could be a slight problem. However, practically, I feel that the string `<!` is clear in intent, and uncommon enough in Markdown, that it shouldn’t cause too much breakage.
Related to GH-620.

Remove superfluous restrictions on declarations

---

spec.txt

for consistency with the rest of the spec.

Change "a HTML block" to "an HTML block"

---

tools/make_spec.lua

Update make_spec.lua to not generate `href` attributes on HTML headings

---

spec.txt

It is tough for something to be "between paragraph", since "paragraph" is singular and there must be at least two of them for something to be between them.

Change paragraph to plural

---

tools/template.html

Adding spaces & "lang" attribute, optimization margins & paddings, etc.

Improved html & css syntax.

---

tools/template.html

This is necessary for comfortable reading of the text on edge and bottom..

Separating text from edge of screen

---

spec.txt

* Remove line tab and form feed from “whitespace”
* Rename `newline` to line feed (the LF, `\n` character) or line ending (the concept)
* Remove the “whitespace” grouping, and be explicit everywhere whether spaces as indentation; spaces; spaces or tabs; spaces, tabs, and up to one line ending; is allowed
* Rename “Punctuation” to “Unicode punctuation”, to disambiguate it more clearly from “ASCII punctuation”
* Reword line breaks, in some cases they meant line endings, blank lines, or either hard or soft line breaks
---
This is a substantial change and needs a thorough review
Open questions:
- Do tabs play a role in how spaces in the inline code span algorithm are stripped and merged?
- What about whitespace in HTML tags? Those are used block HTML of kind 7, which can only be on one line …

Clarify wording in spec for character groups

---

test/normalize.py

This was filed as https://github.com/commonmark/cmark/issues/313 in the `commonmark/cmark` repo, and fixed in https://github.com/commonmark/cmark/commit/68c3a91166347a32a57fb81223750a63cfd92105. This PR merely applies the same patch to `normalize.py` in this repo.

fix `normalize.py` for python 3.8

---

spec.txt

Change link targets in section 2.3 (Container blocks and leaf blocks) to fix links to Container blocks and Leaf blocks.
See: #654

Remove duplicate links in spec

---

spec.txt

The example that illustrates hard breaks cannot occur in code spans, can’t turn into a hard break, as it has a space too few.

Fix missing space

---

spec.txt

Kind 1 HTML now includes `textarea`.
Some other HTML kinds also mention that list, but were not updated.
This commit also orders these raw tag names alphabetically.
Related to: GH-657.
Related to: 24b9d38.

Add `textarea` to more cases

---

spec.txt

Following up on a [conversation on talk.commonmark.org](https://talk.commonmark.org/t/ensure-picture-is-not-parsed-as-block-level-element/4151/7), I'm proposing to update the spec to remove the `source` element as a start condition for HTML blocks.
During my research, I could not find any supporting evidence that it _should_ be starting an HTML block and the fact that it currently does is causing difficult issues when trying to render `<video>`, `<audio>`, or `<picture>` tags. More details are also in the linked discussion.

Remove `source` element as HTML block start condition

---

spec.txt

Hi all,
I'm not a native English speaker, but I think "downside" is one word, not two (as in "down side"). Just noticed this while reading through the spec and I figured I could just create a PR. Feel free to ignore/close this PR if you don't think it is correct.
Thanks for the great work on the spec!
Erik

Fix spelling of "down side" to "downside"

---

spec.txt

*   This limitation is not imposed by block comments
*   This limitation is not imposed by HTML
*   This limitation is not expected to be depended on by authors
Closes GH-712.

Remove restrictive limitation on inline comments

---

spec.txt

Update obsolete link to AsciiDoc. The last Wayback Machine snapshot that seems to work for the old link seem to be from [August 5, 2020](https://web.archive.org/web/20200805202617/http://www.methods.co.nz/asciidoc/).

Update link to AsciiDoc

---

spec.txt

The current commonmark definition of “ASCII punctuation character” does not only include the unicode punctuation characters within the ASCII range, but also the unicode symbol characters within the ASCII range: `$`, `+`, `<`, `=`, `>`, `^`, `` ` ``, `|`, `~`.
I think this makes sense. I think that users would not know the difference, and would indeed expect to be able to escape `*` the same as `$`.
I think it is also sensical to broaden the definition of unicode punctuation the same way, so that there’s no difference between `$`, `£`, and `€`.
Currently:
```markdown
*$*a.
*£*a.
*€*a.
```
*$*a.
*£*a.
*€*a.
Proposed: none turn into `<em>`s (note this is not a useful example, I am sure it could be possible to come up with a better one).
> Note, `S` (symbol) includes the subgroups:
>
> ```
> …
```

Add symbols to unicode punctuation

---

package.json

In `package.json`, `"license": "CC-BY-SA-4.0"` (on line 6), added in commit 0a2d6af (Improved npm package: package.json and index.js., 2016-12-09), was overwritten by the latter, duplicate key `"license": "MIT"` (on line 12).
https://github.com/commonmark/commonmark-spec/blob/51d200052d0ef9ec617907b942ad8d4063874eee/package.json#L6-L12
The result is, npm package `commonmark-spec` is licensed under MIT, not CC-BY-SA 4.0. See https://www.npmjs.com/package/commonmark-spec.
Refer to [related paragraph in RFC 8259][rfc-8259-objects] for JSON format (boldface style added by me),
> An object whose names are all unique is interoperable in the sense
> that all software implementations receiving that object will agree on
> the name-value mappings.  When the names within an object are not
> unique, …

Relicense npm package under CC-BY-SA

---

spec.txt

Unfortunately www.vfmd.org is now showing online bookie info (in Indonesian), hence similar to commit 4e298bf (Use archived gmane links., 2022-01-30), I replaced it with a working archived link closest to the present.

Use archived vfmd link.

---

LICENSE
README.md
package.json
spec.txt
tools/template.html

Convert http to https scheme for all links in the repo, including examples in `spec.txt` (not sure if welcome).
The remaining http schemes are
- a link to `www.aaronsw.com` in `spec.txt` because it doesn't support https,
- all links in `changelog.txt` because I assume released changelog entries should be kept as-is, and
- a link in `CommonMark.dtd` because I know nothing about `.dtd` file format.
```
grep --color=auto --exclude-dir=.git -rnP '(?<!/)http://' .
./spec.txt:1142:[original ATX implementation](http://www.aaronsw.com/2002/atx/atx.py),
./changelog.txt:311:    Discussion at <http://talk.commonmark.org/t/555>.
./changelog.txt:314:    Discussion at <http://talk.commonmark.org/t/779> and
./changelog.txt:315:    <http://talk.commonmark.org/t/1287/12>.
./changelog.txt:346:    See …
```

Use https scheme

---

spec.txt

If my understanding is correct, these unicode symbols should be rendered as-is. But the spec converts all symbols to $.

Fix unicode symbols example in emphasis syntax

---

spec.txt

This result makes sense, since inline HTML being inline implies that it is parsed after block quotes, while block HTML being copy-and-pasteable implies that it should eat Markdown syntax like block quotes. However, pulldown-cmark got this wrong, and apparently so do MD4C, markdown-it, and parsedown, according to [Babelmark 3].
[Babelmark 3]: https://babelmark.github.io/?text=%3Ca%0A%3E%0A%0A%3Cdiv%0A%3E

Add clarifying tests about HTML and block quotes

---

spec.txt

For an inline HTML tag, the `>` must not be at the start of a line.

Fix wrong multi-line HTML tag example

---

spec.txt

The existing sentence (which is formed analogously to the sentences directly above) sounds like an HTML tag is composed of these many things, while the examples show it can be either one of them.

HTML tag: "consists of" → "is"

---

spec.txt

Updates the recommended algorithm to match the current implementation, fixing cases such as `*foo**bar**baz*` (see #801 for full details)
The updated algorithm is based on [Commonmark's JavaScript implementation](https://github.com/commonmark/commonmark.js/blob/master/lib/inlines.js#L441), which I imagine is the same in the other languages. With the alteration, the algorithm successfully converts all of the examples in the spec file.

Update suggested emphasis algorithm
