commonmark/commonmark-spec

man/man3/cmark.3, src/cmark.h, src/iterator.c, src/node.c, src/node.h
Also add another iterator accessor. Fixes issue #287.
=> Add field for user data to node

js/lib/blocks.js
Also, the assignment is unnecessary at this point.
=> Fix incorrect call to addChild with 3 arguments

LICENSE
The "MIT License" first two paragraphs where on a single line.
=> Limit line length to less than 80 characters

spec.txt
Which leads to [link reference definition]. Ironical.
=> Fixed a broken link

spec.txt
This tests for the issue that's fixed in jgm/commonmark.js#49.
=> Add a test for an edge case in link reference parsing.

spec.txt
It's misleading to have a version in master that doesn't reflect the actual released version
=> Add -dev suffix to Spec Version after every release

spec.txt
=> Rename "non-space" to "non-whitespace"

README.md
its very minor but it made me smile reading it
=> consistent usage of we instaed of I

tools/make_spec.lua, tools/template.html
per https://talk.commonmark.org/t/spec-rendered-html-switch/2116/4?u=codinghorror
=> make interact more button-like and clearer

spec.txt
See discussion here: https://github.com/jgm/commonmark.js/issues/103#issuecomment-228888648
=> Allow HTML blocks to end on the last line of their container

spec.txt
Tests 390 and 391 are equal in 0.26.
=> Remove duplicated test.

spec.txt
=> Clarify that some blocks can contain "code spans"

spec.txt
I think this should fix #485.
cc: @shyouhei
=> Clarify definition of delimiter run

spec.txt
Spec suggestion from <https://talk.commonmark.org/t/end-conditions-within-end-conditions/2388/7?u=kivikakk>.
=> Clarify HTML blocks re: "nested" blocks

spec.txt
=> disallow newlines inside of unquoted attrubtes

spec.txt
Based on https://talk.commonmark.org/t/suggestion-of-a-new-example-to-be-put-on-the-specs/2646
=> Add another test case for emphasis

spec.txt
From @johelegp at https://github.com/github/cmark-gfm/pull/157.
=> fix link text grouping sample

spec.txt
=> Add definition of ASCII control characters

spec.txt
=> Fix typo in control characters

spec.txt
=> Remove restriction on list item

spec.txt
=> add inline link examples with empty link text

spec.txt
The examples [176](https://spec.commonmark.org/0.29/#example-176) and [188](https://spec.commonmark.org/0.29/#example-188) show the same input/output, and have similar explanatory intro text.
=> Remove duplicate example

spec.txt
=> Fix wording in start condition of kind 7 HTML

test/cmark.py, test/spec_tests.py
If you like these changes, please merge them without squashing.
=> Improve `spec_tests.py` (refactor, catch invalid utf-8, add `--track`)

spec.txt
There’s a new HTML element in town!
Related-to: whatwg/html#7320.
Realted-to: whatwg/html#5811.
=> Add `search` element to list of known block elements

spec.txt
https://github.com/commonmark/commonmark-spec/releases/tag/0.31.0
=> Fix version
